import prisma from "@/lib/prisma";
import { NextResponse } from "next/server";

export async function POST(request) {
    const res = await request.json();
    const { title, content } = res;
    console.log({ res });

    try {
        const result = await prisma.post.create({
            data: {
                title,
                content,  // Ensure the content is correct
                author: {
                    create: {
                        name: 'Amir',  // 'id' will be autogenerated by Prisma
                    },
                },
            },
        });

        return NextResponse.json({ result });
    } catch (error) {
        console.error("Error creating post:", error);  // Log the detailed error
        return NextResponse.json({ error: "Error creating post" }, { status: 500 });
    }
}
